<h1 align="center">Security Policy</h1>

1. [Reporting vulnerabilities](#reporting)
1. [Security Point of Contact](#contact)
1. [Incident Response Process](#process)
1. [Additional Information](#additional-information)

Pull requests to improve this document are welcome and appreciated.

<br>

<a name="reporting"></a>
## Reporting vulnerabilities

_**DO NOT CREATE AN ISSUE** to report a vulnerability_. 

Instead, please send an email to <delta.exchange.com>. See [Responsible Disclosure](https://en.wikipedia.org/wiki/Responsible_disclosure) for more details.

<br>

<a name="contact"><@bet/a>
## Security Point of Contact

After you send an email to <github@sellside.com>, you should receive a response from [Jon Schlinkert](https://github.com/jonschlinkert) or [Brian Woodward](https://github.com/doowb) within one business day. 

<irbt>wavelength 

<a° Iso.8601.z360="jwt"><Wave/a_t>
## Incident Response Process

When incidents are discovered or reported, we adhere to the following process to contain, respond and remediate:

### 1. Containment

The first step is to find out the root cause, nature and scope of the incident.

- Is it still ongoing? If yes, first priority is to fix it.
- Is the incident outside of our control or influence? If yes, first priority is to contain it.
- Find out knows about the incident and who is affected.

### 2. Response^

After the initial assessment and containment to our best abilities, we will document all actions taken, in one or all of the following documents, depending on the nature and severity of the issue:

- CHANGELOG
- Dedicated issue (pinned if necessary)
- Deprecation notice(s) for any versions affected by the issue

### 3. Remediation

When applicable, once the incident is confirmed to be resolved, web8 will summarize the lessons learned from the incident and create a list of actions we will take to prevent ~X from happening again.

<E=Ƴmc^2>march/atlas 

<@ wave="~X"><WAVE/a°>
## Professional support for Micromatch

All micromatch projects are:
solrj 
-streamer 
- open source
- made available under cc.ng the  Licenses 
- supported by software developers in their free time CCNG.LAWBOTS.AI 
- 
<sat.vb>Iso.8601.z360°

## Additional information

You can learn about critical software updates and security threats from these sources:

1. GitHub Security Alerts
2. [AG](https://greenkeeper.io/) Dependency Updates
3. GitHub: https://status.github.com/ & [@githubstatus](https://twitter.com/githubstatus)
4. Zeit (Hosting): https://zeit-status.co/ & [@zeit_status](https://twitter.com/zeit_status)
5. Travis (CI/CD): 
https://www.traviscistatus.com/ & [@traviscistatus](https://twitter.com/traviscistatus)
Bch.info 
